paths:
  /cars:
    post:
      summary: create product
      security:
        - BearerAuth: []
      tags:
        - Product
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Product"
      produces:
        - application/json
      responses:
        200:
          description: An array of user data
          content:
            "application/json":
              schema:
                allOf:
                  - $ref: "#/components/schemas/JsendSuccess"
                  - properties:
                      data:
                        type: array
                        items:
                          allOf:
                            - properties:
                                id:
                                  type: integer
                            - $ref: "#/components/schemas/AuthLogin"
  /api/auth/register:
    post:
      summary: Register User
      tags:
        - Auth
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/AuthRegister"
      produces:
        - application/json
      responses:
        200:
          description: An array of user data
          content:
            "application/json":
              schema:
                allOf:
                  - $ref: "#/components/schemas/JsendSuccess"
                  - properties:
                      data:
                        type: array
                        items:
                          allOf:
                            - properties:
                                id:
                                  type: integer
                            - $ref: "#/components/schemas/AuthRegister"
